### ISSUE TITLE
Cannot consume scoped service 'AppDBContext' from singleton 'Octokit.Webhooks.WebhookEventProcessor

### ISSUE THREAD

**Issue by PavelBansky** [octokit/webhooks.net#172]
I have a DbContext that is add during ASP .NET Core start

```csharp
        var builder = WebApplication.CreateBuilder(args);
        builder.Services.AddDbContext<AppDBContext>(options =>
             options.UseSqlite(builder.Configuration.GetConnectionString("Default")));
             
        builder.Services.AddSingleton<WebhookEventProcessor, GithubWebhookProcessor>();             
```

Then I have a WebHookProcessor

```csharp
public class GithubWebhookProcessor : WebhookEventProcessor
{
    private readonly AppDBContext _db;

    public GithubWebhookProcessor(AppDBContext dBContext)
    {
        _db = dBContext;
    }    
```

The application fails to start with exception

```
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Octokit.Webhooks.WebhookEventProcessor Lifetime: Singleton ImplementationType: GithubWebhookProcessor': Cannot consume scoped service 'AppDBContext' from singleton 'Octokit.Webhooks.WebhookEventProcessor'.)'
```

Is WebhookEventProcess not designed to work with injected DbContext?

**Comment by JamieMagee** [comment]
I think the main reason I chose singleton lifetime over scoped lifetime for `WebhookEventProcessor` was to avoid constructing `WebhookEventProcessor` for every request. There's no shared state in `WebhookEventProcessor` that would required constructing it fresh for every request.

For your specific case, you can use the [`AddDbContextFactory`][1] extension instead of `AddDbContext`

```c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContextFactory<AppDBContext>(options =>
     options.UseSqlite(builder.Configuration.GetConnectionString("Default")));
     
builder.Services.AddSingleton<WebhookEventProcessor, GithubWebhookProcessor>();
```

Then your `GithubWebhookProcessor` would look like:

```c#
public class GithubWebhookProcessor : WebhookEventProcessor
{
    private readonly IDbContextFactory<AppDBContext> _dbFactory;

    public GithubWebhookProcessor(IDbContextFactory<AppDBContext> dbFactory)
    {
        _dbFactory = dbFactory;
    }
}
```

Then you can call [`CreateDbContext` or `CreateDbContextAsync` on `IDbContextFactory`][2] when you need a DB context. 

[1]: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontextfactory?view=efcore-7.0
[2]: https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.idbcontextfactory-1?view=efcore-7.0

**Comment by PavelBansky** [comment]
Cool. Thank you.
I wasn't sure if I can user the `WebhookEventProcessor` as scoped or not. Ended up using the ContextFactory
