### ISSUE TITLE
[BUG]: ProcessDeployProtectionRuleWebhookAsync seems to have the wrong argument type

### ISSUE THREAD

**Issue by justinmchase** [octokit/webhooks.net#546]
### What happened?

The second argument is of type `DeploymentProtectionRuleEvent` but it should be `DeploymentProtectionRuleRequestedEvent`.

There are a bunch of fields on the payload that are inaccessible as a result.

Bug is on this line:
https://github.com/octokit/webhooks.net/blob/main/src/Octokit.Webhooks/WebhookEventProcessor.cs#L178

Should be:

```cs
            WebhookEventType.DeploymentProtectionRule => JsonSerializer.Deserialize<DeploymentProtectionRuleRequestedEvent>(body)!,
```

### Versions

webhooks.net latest version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by justinmchase** [comment]
I was able to work around this with the following:

```cs
public override WebhookEvent DeserializeWebhookEvent(WebhookHeaders headers, string body)
{
	return headers.Event switch
	{
		"deployment_protection_rule" => JsonSerializer.Deserialize<DeploymentProtectionRuleRequestedEvent>(body),
		_ => base.DeserializeWebhookEvent(headers, body)
	};
}

protected override async Task ProcessDeployProtectionRuleWebhookAsync(
	WebhookHeaders headers,
	DeploymentProtectionRuleEvent deploymentProtectionRuleEvent,
	DeploymentProtectionRuleAction action
)
{
	if (deploymentProtectionRuleEvent is DeploymentProtectionRuleRequestedEvent deploymentProtectionRuleRequestedEvent)
	{
		await ProcessDeployProtectionRuleRequestedAsync(deploymentProtectionRuleRequestedEvent);
	}
}

protected async Task ProcessDeployProtectionRuleRequestedAsync(
	DeploymentProtectionRuleRequestedEvent evt
)
{
	// todo: implement...
}
```

**Comment by JamieMagee** [comment]
I don't think this is a bug. The pattern we're following is that we have a common abstract class that contains all the common properties between each different event action type, and each concrete action type only has the specific properties for the action.

So `DeploymentProtectionRuleEvent` is the abstract base class for the `deployment_protection_rule` event, and `DeploymentProtectionRuleRequestedEvent` is the concrete implementation for the `requested` action. It looks like in this case, all of the properties are on the concrete implementation. But I suspect that's because it's the only action for that event. We don't know what's common until we have 2 actions for an event.

I think your workaround is not so much a workaround, but how I would expect the SDK to be used. All you should need is:

```csharp
protected override async Task ProcessDeployProtectionRuleWebhookAsync(
  WebhookHeaders headers,
  DeploymentProtectionRuleEvent deploymentProtectionRuleEvent,
  DeploymentProtectionRuleAction action
)
{
  if (deploymentProtectionRuleEvent is DeploymentProtectionRuleRequestedEvent deploymentProtectionRuleRequestedEvent)
  {
    // do whatever here
  }
}
```

I think we could also move the properties from `DeploymentProtectionRuleRequestedEvent` to `DeploymentProtectionRuleEvent`, and re-evaluate what is actually common when another action is added for this event.
