### ISSUE TITLE
Support the `merge_group` event

### ISSUE THREAD

**Issue by JamieMagee** [octokit/webhooks.net#77]
### Describe the feature

Users started to receive payloads for this event (See #76). However, the details of this event are not yet in the public documentation[^1]. We should add the full event model once the public documentation is available.

[^1]: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

**Comment by mntlty** [comment]
@JamieMagee when creating the webhook I also created the open api specification for it. I believe this isn't public due to `published: false` here https://github.com/github/github/blob/master/app/api/description/webhooks/merge-group/checks-requested.yaml#L69 but I'm not familiar with how changes to the public docs are made. Can you provide guidance on what is necessary for that to go live?

fyi @willsmythe

**Comment by JamieMagee** [comment]
Unfortunately, I'm not familiar either. I just consume the API 😅

Maybe @nickfloyd knows?

**Comment by wolfy1339** [comment]
The event docs are now public, and I have created schemas over in https://github.com/octokit/webhooks/pull/681
